### ISSUE TITLE
Support for vitest

### ISSUE THREAD

**Issue by eidellev** [timfjord/AnyTest#20]
Hey @timfjord !
I really love this package. Is supporting additional test runners for javascript like `vitest` on your roadmap?

**Comment by timfjord** [comment]
Hey @eidellev 
I am glad that you like the package

I've taken a look at `vitest`, and I think this is something I can do next.

By the way, I might add a few more test frameworks next month, so if you are interested in other test frameworks please let me know so I can prioritize them, as currently I add test frameworks support in a semi-random order

**Comment by timfjord** [comment]
Just merged `vitest` support to main.

Currently, it doesn't support [in-source testing](https://vitest.dev/guide/in-source.html), but I am planning to add this later on https://github.com/timfjord/AnyTest/issues/24

**Comment by timfjord** [comment]
Just released [v0.4.0](https://github.com/timfjord/AnyTest/releases/tag/v0.4.0)
